apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-service
  template:
    metadata:
      labels:
        app: postgres-service
    spec:
      containers:
      - name: postrges-service
        image: postgres:12
        ports:
        - containerPort: 5432
        volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: postgres-pvl
        envFrom:
        - configMapRef:
            name: postgres-configmap
        - secretRef:
            name: postgres-pass
      volumes:
        - name: postgres-pvl
          persistentVolumeClaim:
            claimName: postgres-pvclm
      restartPolicy: Always