apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-start-dpl
  labels:
    app: worker-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-app
  template:
    metadata:
      labels:
        app: worker-app
    spec:
      containers:
      - name: worker-app
        image: epitechcontent/t-dop-600-worker:k8s
        resources:
            limits:
              memory: "256Mi"
        envFrom:
        - secretRef:
            name: postgres-pass
        - configMapRef:
            name: redis-configmap
        - configMapRef:
            name: postgres-configmap
      restartPolicy: Always